# Site settings
title: Life at PathSource
email: nathan@pathsource.com
description: "Pathsource Blog and Timeline"
baseurl: ""
url: "http://pathsource.github.com"

# Build settings
markdown: kramdown
permalink: pretty
